# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.1"
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum groupinstall -y "Development Tools"
    sudo yum install -y ruby
    sudo yum install -y ruby-devel
    gem install fpm
    gem install rake
    gem install package_cloud
  SHELL
end
